# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Izzet.QuotaBubble
PackageVersion: 0.2.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: QuotaBubble.exe
  PortableCommandAlias: quotabubble
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/izzet/quotabubble/releases/download/v0.2.6/QuotaBubble-windows-x64.zip
  InstallerSha256: B768653C983873D035798E5E249DE5432C8571F4398476C22E7D145021260D91
ManifestType: installer
ManifestVersion: 1.12.0
